version: 2.1

executors:
  leiningen:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.3
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    working_directory: /home/circleci/datalog-parser

jobs:
  setup:
    executor: leiningen
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          keys:
            - deps-{{ checksum "project.clj" }}
            - deps-
      - run: lein deps
      - save_cache:
          key: deps-{{ checksum "project.clj" }}
          paths:
            - /home/circleci/.m2
            - /home/circleci/.lein
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - datalog-parser
            - bin

  unittest:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run Unittests
          command: lein test
          no_output_timeout: 5m

  deploy:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          command: lein deploy clojars

workflows:
  build_and_test:
    jobs:
      - setup
      - unittest:
          requires:
            - setup
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - setup
            - unittest
